language: php

php:
  - hhvm
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script :
  - cd webapp; composer install
  - mysql -e 'create database autoeverything_test;'
  - mysql -e "use mysql; SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis'); FLUSH PRIVILEGES;"

script:
  - cd webapp; ./vendor/bin/phpcs --warning-severity=6 --standard=PSR2 webapp/*.php webapp/src webapp/config webapp/public webapp/tests
  - cd webapp; phpunit

notifications:
  email:
    - matthew@baggett.me
  slack: thruio:m7cGYXmdz261AkGDfiRVBHmY
