redis:
  image: redis

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=5aQNxsB58752fN
    - MYSQL_USER=liverpoolfc
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=liverpoolfc

phpmyadmin:
  environment:
   - VIRTUAL_HOST=mysql.automateverything.dev
  expose:
   - '80'
  ports:
   - '80'
  image: matthewbaggett/phpmyadmin:latest
  links:
   - mysql:db

webapp:
  build: webapp/
  ports:
    - "1300:80"
  links:
    - "redis:redis"
    - "mysql:db"
  volumes:
    - ./webapp:/app/
  environment:
   - VIRTUAL_HOST=automateeverything.dev

telegram:
  build: telegram/
  links:
    - "redis:redis"
  volumes:
    - ./telegram:/app/
  environment:
   - BOT_KEY=<REDACTED>