monitor-owl-intuition:
  build: monitors/owl-intuition
  #image: 'automateeverything/monitor-owl-intuition:latest'
  links:
    - redis
  ports:
    - "22600:22600/udp"

monitor-philips-hue:
  build: monitors/philips-hue
  links:
   - redis
   - mysql

monitor-milights:
  build: monitors/milights
  links:
   - redis
   - mysql
  environment:
   - MILIGHTS_HOST=10.0.0.93

monitor-redis:
  build: monitors/redis
  links:
   - redis

#applications-power-alert:
#  build: applications/power-alert
#  links:
#    - redis

applications-rave-generator:
  build: applications/rave-generator
  links:
    - redis

applications-device-list-poller:
  build: applications/device-list-poller
  links:
    - redis

mysql:
  image: 'mysql:latest'
  environment:
    - MYSQL_DATABASE=automate
    - MYSQL_PASSWORD=Gx3Ocw7Jhl9GVNd
    - MYSQL_ROOT_PASSWORD=cN6Dox5UEXZ0VEo
    - MYSQL_USER=automate
  ports:
    - '3306'
  restart: always

phpmyadmin:
  image: 'corbinu/docker-phpmyadmin:latest'
  environment:
    - VIRTUAL_HOST=mysql.ae.dev
  links:
    - mysql
  ports:
    - '80'
  restart: always

redis:
  image: 'redis:latest'
  ports:
    - '1759:6379'

webapp:
  build: ./webapp
  volumes:
   - ./webapp:/app
  links:
    - redis
    - mysql
  environment:
    - VIRTUAL_HOST=ae.dev
    - REALTIME_URL=ae.dev:9998
    #- REDIS_OVERRIDE_HOST=10.0.0.100
    #- REDIS_OVERRIDE_PORT=1759
  ports:
    - '9999:80'
  restart: always

webapp-realtime:
  build: ./webapp-realtime
  links:
    - redis
    - mysql
  environment:
    - DUMMY=veryyes
    #- REDIS_OVERRIDE_HOST=10.0.0.100
    #- REDIS_OVERRIDE_PORT=1759
  ports:
    - '9998:5000'
  restart: always

monitor-ip-camera:
  build: ./monitors/ip-camera
  volumes:
    - ./monitors/ip-camera:/app
    - /scratch/CCTV/videos:/app/videos
  restart: always
  links:
    - redis
  environment:
    - CAMERA_FRONT_HOST=10.0.0.80
    - CAMERA_FRONT_PORT=554
    - CAMERA_FRONT_AUTH=guest:guest
    - CAMERA_FRONT_MEDIAPATH=/onvif1
    - CAMERA_YARD_HOST=10.0.0.81
    - CAMERA_YARD_PORT=554
    - CAMERA_YARD_AUTH=guest:guest
    - CAMERA_YARD_MEDIAPATH=/onvif1
    - CAMERA_DRIVEWAY_HOST=10.0.0.82
    - CAMERA_DRIVEWAY_PORT=554
    - CAMERA_DRIVEWAY_AUTH=guest:guest
    - CAMERA_DRIVEWAY_MEDIAPATH=/onvif1
    - CAMERA_OFFICE_HOST=thruio.plus.com
    - CAMERA_OFFICE_PORT=28000
    - CAMERA_OFFICE_AUTH=guest:guest
    - CAMERA_OFFICE_MEDIAPATH=/onvif1