#monitor-owl-intuition:
#  build: monitors/owl-intuition
#  #image: 'automateeverything/monitor-owl-intuition:latest'
#  #volumes:
#  #  - ./monitors/owl-intuition:/app
#  links:
#    - redis
#  ports:
#    - "22600:22600/udp"
#
#monitor-philips-hue:
#  build: monitors/philips-hue
#  volumes:
#      - ./monitors/philips-hue:/app
#  links:
#   - redis
#   - mysql

#monitor-redis:
#  build: monitors/redis
#  links:
#   - redis

#applications-power-alert:
#  build: applications/power-alert
#  volumes:
#    - ./applications/power-alert:/app
#  links:
#    - redis

mysql:
  image: 'mysql:latest'
  environment:
    - MYSQL_DATABASE=automate
    - MYSQL_PASSWORD=Gx3Ocw7Jhl9GVNd
    - MYSQL_ROOT_PASSWORD=cN6Dox5UEXZ0VEo
    - MYSQL_USER=automate
  ports:
    - '3306'
  restart: always

#phpmyadmin:
#  image: 'corbinu/docker-phpmyadmin:latest'
#  environment:
#    - VIRTUAL_HOST=mysql.ae.dev
#  links:
#    - mysql
#  ports:
#    - '80'
#  restart: always

redis:
  image: 'redis:latest'
  ports:
    - '1759:6379'

webapp:
  build: ./webapp
  volumes:
   - ./webapp:/app
  links:
    - redis
    - mysql
  environment:
    - VIRTUAL_HOST=ae.dev
    - REDIS_OVERRIDE_HOST=10.0.0.99
    - REDIS_OVERRIDE_PORT=1759
  ports:
    - '9999:80'
  restart: always

webapp-realtime:
  build: ./webapp-realtime
  volumes:
   - ./webapp-realtime:/app
  links:
    - redis
    - mysql
  environment:
    - REDIS_OVERRIDE_HOST=10.0.0.99
    - REDIS_OVERRIDE_PORT=1759
  ports:
    - '9998:5000'
  restart: always