monitor-owl-intuition:
  build: monitors/owl-intuition
  #image: 'automateeverything/monitor-owl-intuition:latest'
  #volumes:
  #  - ./monitors/owl-intuition:/app
  links:
    - redis
  ports:
    - "22600:22600/udp"

monitor-redis:
  build: monitors/redis
  links:
   - redis

#mysql:
#  image: 'mysql:latest'
#  environment:
#    - MYSQL_DATABASE=automate
#    - MYSQL_PASSWORD=Gx3Ocw7Jhl9GVNd
#    - MYSQL_ROOT_PASSWORD=cN6Dox5UEXZ0VEo
#    - MYSQL_USER=automate
#  ports:
#    - '3306'
#  restart: always
#phpmyadmin:
#  image: 'corbinu/docker-phpmyadmin:latest'
#  environment:
#    - VIRTUAL_HOST=mysql.ae.dev
#  links:
#    - mysql
#  ports:
#    - '80'
#  restart: always
redis:
  image: 'redis:latest'

